Screen organization data table
alkemyTech/OT217-Client pull request #12
Opened 2022-05-25 18:49 UTC by ms-crist

2022-05-27 00:28 UTC, anagon88 requested changes

2022-05-27 00:28 UTC, anagon88 commented on src/app/core/services/organization.service.ts
> +    //return this._http.get(this.organizationApiUrl);
eliminar codigo comentado

2022-05-27 00:28 UTC, anagon88 commented on src/app/features/pages/home/home.component.html
> +          <img src="assets/LOGO-SOMOS MAS.png" alt="" style="width: 40%;">
mover los style a el archivo css

2022-05-27 00:28 UTC, anagon88 commented on src/app/features/pages/home/home.component.html
> +          <li style="display: flex; margin-left: 20%;"><button class="css-button-arrow--sky">Log in</button></li>
mover todos los style al archivo css

2022-05-27 00:28 UTC, anagon88 commented on src/app/features/pages/organization/edit/organization.component.ts
> +import { Component, OnInit } from '@angular/core';
darle formato al archivo con prettier

2022-05-27 00:28 UTC, anagon88 commented on src/app/features/pages/organization/edit/organization.component.ts
> +      console.log(this.form.value)
eliminar console log

2022-05-27 00:28 UTC, anagon88 commented on src/app/features/pages/organization/edit/organization.component.ts
> +    //showOrganization: any = [];
eliminar codigo comentado

2022-05-27 00:28 UTC, anagon88 commented on src/app/features/pages/organization/organization-list.component.ts
> +      console.log(result);
eliminar console log y dar formato al archivo

2022-05-27 17:12 UTC, anagon88 requested changes

2022-05-27 17:12 UTC, anagon88 commented on src/app/app.module.ts
>  import { NgModule } from '@angular/core';
Importar material module

2022-05-28 01:04 UTC, ms-crist commented on src/app/features/pages/home/home.component.html
> +          <img src="assets/LOGO-SOMOS MAS.png" alt="" style="width: 40%;">
Eso lo solucioné en el componente home, este archivo va atrasado en las versiones

2022-05-28 01:05 UTC, ms-crist commented on src/app/features/pages/home/home.component.html
> +          <li style="display: flex; margin-left: 20%;"><button class="css-button-arrow--sky">Log in</button></li>
Lo mismo que lo anterior, fue solucionado en la rama de home component

2022-05-28 01:32 UTC, anagon88 requested changes
no veo los cambios en esta rama

2022-05-28 16:13 UTC, ms-crist commented
Verifica por favor si es que se realizaron los cambios esta vez Gracias

2022-05-30 20:55 UTC, closed without merging