Ot217 29
alkemyTech/OT217-Client pull request #15
Opened 2022-05-26 17:47 UTC by ralphHuerta

2022-05-27 00:44 UTC, anagon88 requested changes

2022-05-27 00:44 UTC, anagon88 commented on src/app/core/services/listing.service.ts
> +export class Listing{
a qe se refiere con listing?

2022-05-27 00:44 UTC, anagon88 commented on src/app/core/services/update.service.ts
> + /* putActivities(id: string): Observable<any>{
borrar codigo comentaod

2022-05-27 00:44 UTC, anagon88 commented on src/app/core/services/upload.service.ts
> +export class UploadService{
upload q? a q se refiere el servicio? ponerle un nombre mas descripitivo

2022-05-27 00:44 UTC, anagon88 commented on src/app/core/services/upload.service.ts
> +		return new Promise(function(resolve, reject){
no usar promise, mejor usar observables

2022-05-27 00:44 UTC, anagon88 commented on src/app/features/pages/activities/creation-activities/creation-activities.component.html
> +                    <ckeditor [editor]="Editor" data="<p>Hello, world!</p>"  name="description" #description="ngModel"  [(ngModel)]="activities.description" ></ckeditor>
sacar el codgio de data a una variable

2022-05-27 00:44 UTC, anagon88 commented on src/app/features/pages/activities/creation-activities/creation-activities.component.ts
> +    this.activities = new Activities('','','','','','','','','','','');
es necesario esto?

2022-05-27 00:44 UTC, anagon88 commented on src/app/features/pages/activities/creation-activities/creation-activities.component.ts
> +    this.activities = new Activities('','','','','','','','','','','');
no se puede inicializar con un []?

2022-05-27 00:44 UTC, anagon88 commented on src/app/features/pages/activities/creation-activities/creation-activities.component.ts
> +  ngDoCheck(): void {
si va a estar vacio, no implementarlo

2022-05-27 00:44 UTC, anagon88 commented on src/app/features/pages/activities/creation-activities/creation-activities.component.ts
> +        console.log(<any> error)
borrar console log

2022-05-27 00:44 UTC, anagon88 commented on src/app/features/pages/activities/creation-activities/creation-activities.component.ts
> +    this.file.push(archivo)
darle formato al archivo con prettier

2022-05-27 00:44 UTC, anagon88 commented on src/app/features/pages/activities/creation-activities/creation-activities.component.ts
> +          console.log(<any> error)
borrar console log

2022-05-27 03:56 UTC, ralphHuerta commented on src/app/core/services/listing.service.ts
> +export class Listing{
Es el listado de todos los get de activities

2022-05-27 04:00 UTC, ralphHuerta commented on src/app/core/services/upload.service.ts
> +export class UploadService{
Era un componente para cargar imágenes, pero ya no lo utilice

2022-05-28 01:34 UTC, anagon88 commented on src/app/core/services/listing.service.ts
> +export class Listing{
entocnes capaz un mejor nombre no es ListingActivities? Igualmente estaria bueno crear un servicio ActivitiesServices y ahi implementar no solo el listado sino los endpoints que despeus necesitas

2022-05-28 01:37 UTC, anagon88 requested changes

2022-05-28 01:37 UTC, anagon88 commented on src/app/core/services/update.service.ts
> +import { HttpClient, HttpHeaders } from "@angular/common/http";
unir este servicio con el de listing y llamarlos ActivitiesService y ahi tener las dos funciones listing y update

2022-05-28 01:37 UTC, anagon88 commented on src/app/features/features.module.ts
> +    AppRoutingModule,
Fijate que hay un module que tiene todo lo de material e importar ese modulo aca

2022-05-28 01:37 UTC, anagon88 commented on src/app/features/pages/activities/creation-activities/creation-activities.component.ts
> +    this.activities = new Activities('','','','','','','','','','','');
cambiar a this.activities = [];

2022-05-29 23:05 UTC, ralphHuerta commented on src/app/features/features.module.ts
> +    AppRoutingModule,
Este lo are cuando haga el marge porque aun en esta versión no existe ese modulo

2022-05-30 02:45 UTC, anagon88 approved these changes
dar formato al documentoindicado y luego aprobado para mergear

2022-05-30 02:45 UTC, anagon88 commented on src/app/features/pages/activities/creation-activities/creation-activities.component.ts
> +      this.putActivities(this.id)
dar formato al documento

2022-05-31 02:47 UTC, merged