Ot217 57
alkemyTech/OT217-Client pull request #2
Opened 2022-05-21 02:42 UTC by filburt88

Activities-Page created - with pagination and styles.
* Service created to bring data from API/activities and rendering cards
* Activities-card added with Inputs, to add reusability.
* AOS library added just for styling effect on rendering view
* material module added (this must be erased when launching to production)
* Activity Interface created.

2022-05-21 18:47 UTC, anagon88 requested changes
Mover la historia de usuario a la columna Code Review (tercer columna) y adjuntar a este pull request la evidencia (screenshots la funcionalidad terminada)

2022-05-21 18:47 UTC, anagon88 commented on src/app/material/material.module.ts
> +import { NgModule } from '@angular/core';
Estas seguro que se necesita todos estos modulos? Agregar solo los que se van usando

2022-05-21 20:06 UTC, filburt88 commented on src/app/material/material.module.ts
> +import { NgModule } from '@angular/core';
Ya borré los módulos que no usaba.

2022-05-21 20:08 UTC, filburt88 commented
Componente funcionando:

![OT217-57 Mobile View](https://user-images.githubusercontent.com/77215052/169667401-f0f5a020-d6c2-43a4-acdd-c5bdb70918ea.png)

![OT217-57 desktop-view](https://user-images.githubusercontent.com/77215052/169667403-b1ff8597-40db-45d8-926b-9215e7c46eb4.png)

2022-05-22 22:44 UTC, anagon88 approved these changes

2022-05-24 00:48 UTC, merged