create a form contact
alkemyTech/OT217-Client pull request #6
Opened 2022-05-22 01:14 UTC by MatiasDevA

+ Create a new form contact

+**EVIDENCE.**
![form contac](https://user-images.githubusercontent.com/98768529/169674171-94644475-e39d-4c68-ae34-702ab90cf98e.png)

2022-05-23 17:24 UTC, anagon88 requested changes

2022-05-23 17:24 UTC, anagon88 commented on src/app/features/pages/form-contact/form-contact.component.ts
> +    console.log("message");
eliminar console log

2022-05-23 17:24 UTC, anagon88 commented on src/app/features/pages/form-contact/form-contact.component.ts
> +
usar prettier

2022-05-23 17:24 UTC, anagon88 commented on src/app/features/pages/form-contact/form-contact.component.ts
> +
usar prettier

2022-05-23 17:24 UTC, anagon88 commented on src/app/features/pages/form-contact/form-contact.component.ts
> +
ngoninit no impleentar si no lo usas

2022-05-23 17:24 UTC, anagon88 commented on src/app/features/pages/form-contact/form-contact.component.html
> +          <textarea class="form-control"  id="floatingTextarea2" style="height: 100px" formControlName="message" ></textarea>
estilos que vayan en la hoja de estilos

2022-05-23 20:02 UTC, MatiasDevA commented on src/app/features/pages/form-contact/form-contact.component.html
> +          <textarea class="form-control"  id="floatingTextarea2" style="height: 100px" formControlName="message" ></textarea>
ya modifique los archivos.

2022-05-24 02:09 UTC, anagon88 approved these changes

2022-05-26 02:02 UTC, merged