Leer los terminos y condiciones de la ONG Ot217 121
alkemyTech/OT217-Client pull request #75
Opened 2022-06-13 19:09 UTC by ms-crist

Evidence
![terminos y condiciones](https://user-images.githubusercontent.com/81595403/173426915-76a6241b-6908-4330-92e6-6d825534154f.png)

2022-06-14 03:30 UTC, anagon88 requested changes

2022-06-14 03:30 UTC, anagon88 commented on src/app/features/components/dialog-content-pdf/dialog-content-pdf.component.ts
> +  src = './assets/terms.pdf';
esto se usa? formatear el documento

2022-06-14 03:30 UTC, anagon88 commented on src/app/features/components/dialog-content-pdf/dialog-pdf-open/dialog-pdf-open.component.ts
> +      console.log(res);
eliminar estas lineas vacias

2022-06-17 21:38 UTC, ms-crist commented on src/app/features/components/dialog-content-pdf/dialog-content-pdf.component.ts
> +  src = './assets/terms.pdf';
Si se usa es la ruta al documento pdf

2022-06-19 15:52 UTC, anagon88 approved these changes

2022-06-19 15:52 UTC, merged