Ot217 132
alkemyTech/OT217-Client pull request #90
Opened 2022-06-17 04:40 UTC by MatiasDevA

Tarea OT217-132 Y OT127-136
EVIDENCIA
![sin textooo](https://user-images.githubusercontent.com/98768529/174226167-9745e4ab-8485-46d3-a178-cfa52293d1de.png)
![sin text](https://user-images.githubusercontent.com/98768529/174226178-9bf63c09-26a2-4b00-b932-a00199189aa9.png)

2022-06-17 17:54 UTC, anagon88 requested changes

2022-06-17 17:54 UTC, anagon88 commented on angular.json
> +              "./node_modules/leaflet/dist/leaflet.css"
esta bien que se eliminen los otros links? capaz fue un problema de mergeo

2022-06-17 17:54 UTC, anagon88 commented on src/app/core/services/authGoogle.service.ts
> +//import { AngularFireAuth } from "@angular/fire/compat/auth";
esta bien esto comentado?

2022-06-17 17:54 UTC, anagon88 commented on src/app/features/pages/public-pages/auth/auth-google/auth-google.component.ts
> +  // IngresarGoogle() {
No subir codigo comentado

2022-06-17 22:13 UTC, MatiasDevA commented on angular.json
> +              "./node_modules/leaflet/dist/leaflet.css"
sii, los elimine porque los había implementado antes, pero  después no use  primeng.

2022-06-17 22:14 UTC, MatiasDevA commented on src/app/features/pages/public-pages/auth/auth-google/auth-google.component.ts
> +  // IngresarGoogle() {
los codigos comentados eran porque en el main algo andaba mal y no me andaba el ng serve

2022-06-19 15:54 UTC, anagon88 approved these changes

2022-06-19 15:55 UTC, anagon88 commented on src/app/features/pages/public-pages/auth/auth-google/auth-google.component.ts
> +  // IngresarGoogle() {
claro, cuando haces el pr asegurate de estos cambios temporales no subirlos

2022-06-20 02:53 UTC, merged